# Generated by Django 3.0.7 on 2020-08-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='checkbox',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
