# Generated by Django 3.0.7 on 2020-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0002_auto_20200815_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='checkbox',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
